apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: smoker-topic-usr1-2-usr2
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
 

